services:
  passivbot:
    build: .
    container_name: passivbot
    restart: unless-stopped
    volumes:
      - ./:/app/
    command:
      - /bin/sh
      - -c
      - |
        python passivbot.py binance_01 DOGEUSDT configs/backtest/dogebest.json
    
