services:
  passivbot:
    build: .
    container_name: passivbot
    restart: unless-stopped
    volumes:
      - ./:/app/
    command:
      - /bin/sh
      - -c
      - |
        python passivbot.py binance_01 ATOMUSDT configs/backtest/ATOMUSDT.json &
        python passivbot.py binance_01 MATICUSDT configs/backtest/MATICUSDT.json &
        python passivbot.py binance_01 AMBUSDT configs/backtest/AMBUSDT.json 
    
