services:
  passivbot:
    build: .
    container_name: passivbot
    restart: unless-stopped
    volumes:
      - ./:/app/
    command:
      - /bin/sh
      - -c
      - |
        python passivbot.py binance_01 ATOMUSDT configs/backtest/ATOMUSDT.json &
        python passivbot.py binance_01 MATICUSDT configs/backtest/MATICUSDT.json &
        python passivbot.py binance_01 AMBUSDT configs/backtest/AMBUSDT.json &
        python passivbot.py binance_01 RLCUSDT configs/backtest/RLCUSDT.json &
        python passivbot.py binance_01 ANKRUSDT configs/backtest/ANKRUSDT.json &
        python passivbot.py binance_01 ADAUSDT configs/backtest/ADAUSDT.json &
        python passivbot.py binance_01 CHZUSDT configs/backtest/CHZUSDT.json &
        python passivbot.py binance_02 1000SHIBUSDT configs/backtest/yasmin/1000SHIBUSDT.json &
        python passivbot.py binance_02 MATICUSDT configs/backtest/yasmin/MATICUSDT.json
    
